// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzibhxlfwadjpufpgegj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6aWJoeGxmd2FkanB1ZnBnZWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTYzNTksImV4cCI6MjA1NTg3MjM1OX0.p5tLhjprj0gK1q9we1pSZ92pJPn1mGxdoyWVDFvyeNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);